FROM node:12.13.0-stretch-slim

RUN npm install -g typescript
RUN npm install -g @nestjs/cli
RUN npm install -g rimraf
RUN npm install -g copyfiles
RUN npm install -g prettier
RUN npm install -g ts-node
# tar and bzip2 are required to install for phantomJs, libfontconfig for use it
# git nano installed in case of debug
RUN apt-get update && apt-get install -y \
	tar \
	bzip2 \
	libfontconfig \
	nano \
	git \
	&& rm -rf /var/lib/apt/lists/*